In [1]:
#Q. 1) What are all different subjects for which Udemy is offering courses ?
#Q. 2) Which subject has the maximum number of courses.
#Q. 3) Show all the courses which are Free of Cost.
#4) Show #Q. all the courses which are Paid.
#Q. 5) Which are Top Selling Courses ?
#Q. 6) Which are Least Selling Courses ?
#Q. 7) Show all courses of Graphic Design where the price is below 100 ?
#Q. 8) List out all the courses that are related to 'Python'.
#Q. 9) What are courses that were published in the year 2015 ?
#Q. 10) What is the Max. Number of Subscribers for Each Level of courses ?

In [3]:
import seaborn as sns
import matplotlib as plt
import pandas as pd
df=pd.read_csv("7. Udemy Courses.csv")
#print(df)
df.count()
df.isnull().sum()
df.head()
#IMP FOR STARTING A PROJECT ANALYSIS

,course_id,course_title,is_paid,price,num_subscribers,num_reviews,num_lectures,level,content_duration,published_timestamp,subject
0,288942,#1 Piano Hand Coordination: Play 10th Ballad i...,True,35,3137,18,68,All Levels,1.5 hours,2014-09-18T05:07:05Z,Musical Instruments
1,1170074,#10 Hand Coordination - Transfer Chord Ballad ...,True,75,1593,1,41,Intermediate Level,1 hour,2017-04-12T19:06:34Z,Musical Instruments
2,1193886,#12 Hand Coordination: Let your Hands dance wi...,True,75,482,1,47,Intermediate Level,1.5 hours,2017-04-26T18:34:57Z,Musical Instruments
3,1116700,#4 Piano Hand Coordination: Fun Piano Runs in ...,True,75,850,3,43,Intermediate Level,1 hour,2017-02-21T23:48:18Z,Musical Instruments
4,1120410,#5 Piano Hand Coordination: Piano Runs in 2 ...,True,75,940,3,32,Intermediate Level,37 mins,2017-02-21T23:44:49Z,Musical Instruments

In [3]:
#Q. 1) What are all different subjects for which Udemy is offering courses ?
df.groupby('subject').count()

,course_id,course_title,is_paid,price,num_subscribers,num_reviews,num_lectures,level,content_duration,published_timestamp
subject,,,,,,,,,,
Business Finance,1199,1199,1199,1199,1199,1199,1199,1199,1199,1199
Graphic Design,603,603,603,603,603,603,603,603,603,603
Musical Instruments,680,680,680,680,680,680,680,680,680,680
Web Development,1200,1200,1200,1200,1200,1200,1200,1200,1200,1200

In [5]:
df.groupby('subject').course_id.count().sort_values(ascending=False)
#df.groupby('Region').Confirmed.sum().sort_values(ascending=False).head(10)

subject
Web Development        1200
Business Finance       1199
Musical Instruments     680
Graphic Design          603
Name: course_id, dtype: int64

In [15]:
#show all the coures which r free f cost.
df[df.is_paid==False]

,course_id,course_title,is_paid,price,num_subscribers,num_reviews,num_lectures,level,content_duration,published_timestamp,subject
41,286070,5 lecciones que todo guitarrista debe tomar,False,Free,4452,263,14,Beginner Level,1 hour,2014-08-23T05:08:14Z,Musical Instruments
49,696630,"7 Ways A Beginner Guitarist Can Sound Better, ...",False,Free,4529,193,7,Beginner Level,36 mins,2015-12-21T18:50:50Z,Musical Instruments
57,955914,A beginner`s guide to fingerpicking and strumm...,False,Free,3481,29,20,Beginner Level,2 hours,2016-09-13T21:51:59Z,Musical Instruments
67,270976,A how to guide in HTML,False,Free,7318,205,8,Beginner Level,35 mins,2014-08-10T20:19:10Z,Web Development
74,1214144,¡Triunfar en La Bolsa de Valores No Requiere d...,False,Free,338,7,6,Beginner Level,1 hour,2017-05-30T14:30:12Z,Business Finance
...,...,...,...,...,...,...,...,...,...,...,...
3620,552598,WordPress in under an hour - Create/manage you...,False,Free,6474,86,15,All Levels,1 hour,2015-07-15T00:21:56Z,Web Development
3638,1068590,Wordpress Website Mastery 2017,False,Free,5181,64,22,Beginner Level,2.5 hours,2017-01-18T17:01:40Z,Web Development
3652,752706,Write quicker HTML5 and CSS 3; productivity ha...,False,Free,13016,286,15,All Levels,1.5 hours,2016-03-03T17:45:31Z,Web Development
3674,1257976,Your First 10 Guitar Lessons - Learn how to pl...,False,Free,924,4,18,Beginner Level,1 hour,2017-06-29T00:29:36Z,Musical Instruments
3680,1225194,Zoho Books Gestion Financière d'Entreprise pas...,False,Free,229,0,33,All Levels,2 hours,2017-05-26T16:45:55Z,Business Finance

In [16]:
#4) Show all the courses which are Paid.
df[df.is_paid==True]

,course_id,course_title,is_paid,price,num_subscribers,num_reviews,num_lectures,level,content_duration,published_timestamp,subject
0,288942,#1 Piano Hand Coordination: Play 10th Ballad i...,True,35,3137,18,68,All Levels,1.5 hours,2014-09-18T05:07:05Z,Musical Instruments
1,1170074,#10 Hand Coordination - Transfer Chord Ballad ...,True,75,1593,1,41,Intermediate Level,1 hour,2017-04-12T19:06:34Z,Musical Instruments
2,1193886,#12 Hand Coordination: Let your Hands dance wi...,True,75,482,1,47,Intermediate Level,1.5 hours,2017-04-26T18:34:57Z,Musical Instruments
3,1116700,#4 Piano Hand Coordination: Fun Piano Runs in ...,True,75,850,3,43,Intermediate Level,1 hour,2017-02-21T23:48:18Z,Musical Instruments
4,1120410,#5 Piano Hand Coordination: Piano Runs in 2 ...,True,75,940,3,32,Intermediate Level,37 mins,2017-02-21T23:44:49Z,Musical Instruments
...,...,...,...,...,...,...,...,...,...,...,...
3676,498488,Your First Successful Forex Trades - With Case...,True,200,1079,34,16,All Levels,2.5 hours,2015-05-26T20:48:48Z,Business Finance
3677,328960,Your Own Site in 45 Min: The Complete Wordpres...,True,120,1566,29,36,All Levels,4 hours,2015-04-20T22:15:17Z,Web Development
3678,552700,Your Second Course on Piano: Two Handed Playing,True,70,1018,12,22,Beginner Level,5 hours,2015-10-26T20:04:21Z,Musical Instruments
3679,631754,Zend Framework 2: Learn the PHP framework ZF2 ...,True,40,723,130,37,All Levels,6.5 hours,2015-11-11T18:55:45Z,Web Development
3681,964478,Zombie Apocalypse Photoshop Actions,True,50,12,1,15,All Levels,1.5 hours,2016-09-26T22:19:48Z,Graphic Design

In [31]:
#Q. 5) Which are Top Selling Courses ?
df.sort_values('num_subscribers',ascending=False).head(5)
#Q. 6) Which are Least Selling Courses ?
df.sort_values('num_subscribers',ascending=True).head(5)

,course_id,course_title,is_paid,price,num_subscribers,num_reviews,num_lectures,level,content_duration,published_timestamp,subject
649,1233314,Building a Balanced Scorecard,True,50,0,0,11,Intermediate Level,2 hours,2017-07-03T21:38:22Z,Business Finance
3259,1232282,The Cash Flow Statement - An Introduction,True,50,0,0,10,Beginner Level,1.5 hours,2017-06-28T16:05:51Z,Business Finance
3261,1275872,The Complete Adobe Spark Course,True,150,0,0,29,All Levels,2 hours,2017-07-03T17:39:57Z,Graphic Design
910,726314,Create Beautiful Image Maps for Your Website,True,20,0,0,8,Intermediate Level,37 mins,2016-01-18T17:56:36Z,Graphic Design
3328,715476,The Cuckoo Strategy to get European Funding,True,160,0,0,6,All Levels,1 hour,2016-01-06T02:38:23Z,Business Finance

In [30]:
#Q. 7) Show all courses of Graphic Design where the price is below 100 ?
df[(df['price']<'100') | (df['subject']=='Graphic Design')]

,course_id,course_title,is_paid,price,num_subscribers,num_reviews,num_lectures,level,content_duration,published_timestamp,subject
8,206592,:::Beginners Guide To Creating Amazing Images ...,True,25,72,5,17,Beginner Level,1 hour,2014-04-29T19:50:31Z,Graphic Design
20,1165268,15 Motion Graphic Elements in After Effect (S...,True,30,8,0,20,Intermediate Level,3 hours,2017-04-11T04:27:34Z,Graphic Design
35,1164876,3DS MAX - Learn 3Ds MAX tutorial for Beginners...,True,20,785,2,29,All Levels,4.5 hours,2017-04-18T16:45:59Z,Graphic Design
39,599652,48 Logo Designs and Techniques,True,20,113,9,48,All Levels,9 hours,2015-09-15T00:23:14Z,Graphic Design
47,1269190,7 Secrets To Designing In Black and White,True,100,1000,1,12,All Levels,1.5 hours,2017-06-27T19:55:18Z,Graphic Design
...,...,...,...,...,...,...,...,...,...,...,...
3588,1131780,"Whiteboard Animation, Beginner To Expert - In ...",True,20,1343,25,16,All Levels,1 hour,2017-03-14T20:52:30Z,Graphic Design
3594,908664,Word Swag : Create Stunning Images with the Wo...,True,100,2416,19,14,All Levels,1 hour,2016-08-09T17:56:53Z,Graphic Design
3639,1122306,Wordpress: Comment utiliser le thème FABLE,True,20,1,0,10,Beginner Level,39 mins,2017-03-07T16:53:27Z,Graphic Design
3671,144222,"YOU can Draw, Shade and Paint a Mixed Media Gi...",True,30,1249,44,19,Beginner Level,3 hours,2014-01-28T02:30:26Z,Graphic Design
3681,964478,Zombie Apocalypse Photoshop Actions,True,50,12,1,15,All Levels,1.5 hours,2016-09-26T22:19:48Z,Graphic Design

In [3]:
#Q. 8) List out all the courses that are related to 'Python
df[df.course_title.str.contains('python')]

Empty DataFrame
Columns: [course_id, course_title, is_paid, price, num_subscribers, num_reviews, num_lectures, level, content_duration, published_timestamp, subject]
Index: []

In [10]:
#Q. 9) What are courses that were published in the year 2015 ?
df[df.published_timestamp=='2015']

Empty DataFrame
Columns: [course_id, course_title, is_paid, price, num_subscribers, num_reviews, num_lectures, level, content_duration, published_timestamp, subject]
Index: []

In [6]:
#Q. 10) What is the Max. Number of Subscribers for Each Level of courses ?
df.sort_values('num_subscribers',ascending=False)

,course_id,course_title,is_paid,price,num_subscribers,num_reviews,num_lectures,level,content_duration,published_timestamp,subject
2230,41295,Learn HTML5 Programming From Scratch,False,Free,268923,8629,45,All Levels,10.5 hours,2013-02-14T07:03:41Z,Web Development
776,59014,Coding for Entrepreneurs Basic,False,Free,161029,279,27,Beginner Level,3.5 hours,2013-06-09T15:51:55Z,Web Development
3385,625204,The Web Developer Bootcamp,True,200,121584,27445,342,All Levels,43 hours,2015-11-02T21:13:27Z,Web Development
640,173548,Build Your First Website in 1 Week with HTML5 ...,False,Free,120291,5924,30,Beginner Level,3 hours,2014-04-08T16:21:30Z,Web Development
3316,764164,The Complete Web Developer Course 2.0,True,200,114512,22412,304,All Levels,30.5 hours,2016-03-08T22:28:36Z,Web Development
...,...,...,...,...,...,...,...,...,...,...,...
1267,1258666,Financial Statement Auditing Cycles,True,50,0,0,9,Intermediate Level,2 hours,2017-06-29T23:20:10Z,Business Finance
2070,1215926,Kickstarter success in 5 easy steps,True,20,0,0,12,All Levels,31 mins,2017-05-16T14:55:28Z,Business Finance
1931,1247992,Introduction to Project Management for Finance...,True,50,0,0,9,Beginner Level,2 hours,2017-07-03T21:40:32Z,Business Finance
2380,1224186,Learn to Play Piano Like a Pro - Easy Piano Co...,True,35,0,0,13,Beginner Level,31 mins,2017-05-30T00:19:02Z,Musical Instruments
3165,1087466,Stop Creditors from Harassing you and Avoid Ba...,True,20,0,0,7,Beginner Level,37 mins,2017-02-02T16:22:37Z,Business Finance